<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="generator" content="pandoc">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
  <link rel="icon" href="../favicon.ico" />
  <link rel="stylesheet" href="../style.css">
  <title>予期しないリターン (LocalJumpError) | Techioz</title>
  <style type="text/css">code{white-space: pre;}</style>
  <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1637770322917058"
     crossorigin="anonymous"></script>
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-DRM1ZRNLDN"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-DRM1ZRNLDN');
  </script>
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Article",
  "headline": "予期しないリターン (LocalJumpError)",
  "author": {
    "@type": "Person",
    "address": "",
    "email": null,
    "identifier": "masyumaroking",
    "name": "masyumaroking"
  },
  "publisher": {
    "@type": "Person",
    "name": "masyumaroking"
  }
}
</script>
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
</head>
<body>
  <header>
    <div class="container">
        <h1>Techioz Blog</h1>
        <nav>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">Articles</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </nav>
    </div>
  </header>
  <main>
    <div class="container">
        <article>
                      <h2>予期しないリターン (LocalJumpError)</h2>
                    <h2 id="概要">概要</h2>
                    <p>この Ruby 2.0
                    コードにはどのような問題があるのでしょうか?</p>
                    <pre><code>p (1..8).collect{|denom|
    (1...denom).collect{|num|
        r = Rational(num, denom)
        if r &gt; Rational(1, 3) and r &lt; Rational(1, 2)
            return 1
        else
            return 0
        end
    }
}.flatten
</code></pre>
                    エラーは
                    <main>
                    <p>のブロック (2 レベル) にあります: 予期しない戻り
                    (LocalJumpError)。 n 個の 1 (および残りの 0)
                    を含むフラット
                    リストを作成したいと考えています。ここで、n は分母が
                    8 未満で 1/3 から 1/2 までの有理数の数です。
                    (これはプロジェクト
                    オイラーの問題です)。なのでインナーブロックから戻ろうとしています。</p>
                    <h2 id="解決策">解決策</h2>
                    <p>Ruby*
                    ではブロック内に戻ることはできません。最後のステートメントが戻り値になるため、この場合は
                    return ステートメントを削除するだけです。</p>
                    <pre><code>p (1..8).collect{|denom|
    (1...denom).collect{|num|
        r = Rational(num, denom)
        if r &gt; Rational(1, 3) and r &lt; Rational(1, 2)
            1
        else
            0
        end
    }
}.flatten
</code></pre>
                    <p>*: lambda ブロック内で次のように実行できます:
                    lambda { return “foo” }.call # =&gt;
                    “foo”。これはスコープ設定などに関係しており、これがラムダ
                    ブロックと proc ブロックの主な違いの 1
                    つです。メソッドに渡す「通常の」ブロックは、proc
                    ブロックに似ています。</p>
        </article>
    </div>
  </main>
  <footer>
    <div class="container">
        <p>&copy; 2024 Techioz. All rights reserved.</p>
    </div>
  </footer>
</body>
</html>