<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="generator" content="pandoc">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
  <link rel="icon" href="../favicon.ico" />
  <link rel="stylesheet" href="../style.css">
  <title>メソッドでエラーが発生したにもかかわらず、Rspec raise_error テストが失敗する | Techioz</title>
  <style type="text/css">code{white-space: pre;}</style>
  <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1637770322917058"
     crossorigin="anonymous"></script>
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-DRM1ZRNLDN"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-DRM1ZRNLDN');
  </script>
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Article",
  "headline": "メソッドでエラーが発生したにもかかわらず、Rspec raise_error テストが失敗する",
  "author": {
    "@type": "Person",
    "address": "",
    "email": null,
    "identifier": "masyumaroking",
    "name": "masyumaroking"
  },
  "publisher": {
    "@type": "Person",
    "name": "masyumaroking"
  }
}
</script>
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
</head>
<body>
  <header>
    <div class="container">
        <h1>Techioz Blog</h1>
        <nav>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">Articles</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </nav>
    </div>
  </header>
  <main>
    <div class="container">
        <article>
                      <h2>メソッドでエラーが発生したにもかかわらず、Rspec
raise_error テストが失敗する</h2>
                    <h2 id="概要">概要</h2>
                    <p>私のテストは次のようになります。</p>
                    <p>「非サブスクリプションまたは試用メンバーシップを渡すとエラーが返されます」
                    Expect(helper.description_for_subscription(繰り返しプラン)).to
                    raise_error(RuntimeError) 終わり</p>
                    <p>私のメソッドはこれを返します:</p>
                    <p>失敗 「サブスクリプション モデル
                    タイプが不明です!」</p>
                    <p>しかし、Rspec
                    は次のような失敗メッセージを返します。</p>
                    <p>失敗/エラー:
                    Expect(helper.description_for_subscription(quiring_plan)).to
                    raise_error(RuntimeError) ランタイムエラー：
                    サブスクリプション モデルの種類が不明です。</p>
                    <p>何が起こっているのか？？</p>
                    <h2 id="解決策">解決策</h2>
                    <p>() の代わりに {}
                    を使用して、期待値をブロック内にラップする必要があります。</p>
                    <pre><code>expect{
  helper.description_for_subscription(recurring_plan)
}.to raise_error(RuntimeError)
</code></pre>
                    <p>ここで「予期されるエラー」セクションを確認してください</p>
        </article>
    </div>
  </main>
  <footer>
    <div class="container">
        <p>&copy; 2024 Techioz. All rights reserved.</p>
    </div>
  </footer>
</body>
</html>