<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="generator" content="pandoc">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
  <link rel="icon" href="../favicon.ico" />
  <link rel="stylesheet" href="../style.css">
  <title>Rescuable モジュールを含めると機能しないのはなぜですか? | Techioz</title>
  <style type="text/css">code{white-space: pre;}</style>
  <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1637770322917058"
     crossorigin="anonymous"></script>
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-GV53GJEY2E"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-GV53GJEY2E');
  </script>
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Article",
  "headline": "Rescuable モジュールを含めると機能しないのはなぜですか?",
  "author": {
    "@type": "Person",
    "address": "",
    "email": null,
    "identifier": "masyumaroking",
    "name": "masyumaroking"
  },
  "publisher": {
    "@type": "Person",
    "name": "masyumaroking"
  }
}
</script>
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
</head>
<body>
  <header>
    <div class="container">
        <h1>Techioz Blog</h1>
        <nav>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">Articles</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </nav>
    </div>
  </header>
  <main>
    <div class="container">
        <article>
                      <h2>Rescuable
モジュールを含めると機能しないのはなぜですか?</h2>
                    <h2 id="概要">概要</h2>
                    <pre><code>class MyKlass

  include ActiveSupport::Rescuable

  rescue_from Exception do
    return &quot;rescued&quot;
  end

  #other stuff
end
</code></pre>
                    <p>MyKlass は純粋な Ruby オブジェクトですが、Rails
                    アプリケーション内で定義されています。</p>
                    <p>Rails コンソールで MyKlass
                    インスタンスを呼び出して、確実に例外を発生させるメソッドを適用しようとすると、救済されると期待されるエラー以外は何も起こりません。</p>
                    <h2 id="解決策">解決策</h2>
                    <p>使用方法は次のとおりです。</p>
                    <pre><code>class MyKlass
  include ActiveSupport::Rescuable
  # define a method, which will do something for you, when exception is caught
  rescue_from Exception, with: :my_rescue

  def some_method(&amp;block)
    yield
  rescue Exception =&gt; exception
    rescue_with_handler(exception) || raise
  end

  # do whatever you want with exception, for example, write it to logs
  def my_rescue(exception)
    puts &quot;Exception caught! #{exception.class}: #{exception.message}&quot;
  end
end

MyKlass.new.some_method { 0 / 0 }
# Exception caught! ZeroDivisionError: divided by 0
#=&gt; true
</code></pre>
                    <p>例外の救出は犯罪であることは言うまでもありません。</p>
        </article>
    </div>
  </main>
  <footer>
    <div class="container">
        <p>&copy; 2024 Techioz. All rights reserved.</p>
    </div>
  </footer>
</body>
</html>